version: "3.8"
services:
  web:
    build: .
    command: gunicorn todo_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A todo_backend worker -l info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

  beat:
    build: .
    command: celery -A todo_backend beat -l info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
